<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Confirm Email</name>
   <tag></tag>
   <elementGuidId>7544c6c5-35b4-40a6-8edc-5d47da297da9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.hooq.tv/verify/email?h=eyJvdHAiOiIzMjQ0MzYiLCJoYXNoIjoiMnlVM29CQWlFOUdDenFLa1k5MXNLdGptbnNZPSIsInNpZ25hdHVyZSI6IjlkMDVjM2Q5NDczODJmMDI5YjkxNGFlZThkZDU3MjA5MTMxNDFhOTQ5ZGQ4ZjJkZjk0NTI1MDRiYjg3ZDMxNGYiLCJlbWFpbCI6ImF1bGlhLnNvZGlxaW5AeWFob28uY28uaWQiLCJjb3VudHJ5IjoiSUQiLCJhY3Rpb24iOiJzaWduaW4ifQ==</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yiv3059838543&quot;)/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[3]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
